# Generated by Django 5.2.8 on 2025-12-10 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding', models.JSONField()),
                ('page_number', models.IntegerField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfs.pdf')),
            ],
        ),
    ]
