# Generated by Django 5.2.8 on 2025-12-10 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0002_pdfchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfchunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfchunk',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
