# Generated by Django 5.2.8 on 2025-12-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0003_pdfchunk_created_at_alter_pdfchunk_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfchunk',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
